import fs from "fs";
import path from "path";
import { task } from "hardhat/config";
import { HardhatRuntimeEnvironment } from "hardhat/types";

/**
 * Generate frontend artifacts (ABI and addresses) from deployment files
 * This script reads existing deployments and generates TypeScript files for the frontend
 */
async function generateFrontendArtifacts(hre: HardhatRuntimeEnvironment) {
  const deploymentsDir = path.join(__dirname, "..", "deployments");
  const frontendDir = path.join(__dirname, "..", "..", "frontend");
  const frontendContractsDir = path.join(frontendDir, "contracts");

  // Create contracts directory if it doesn't exist
  if (!fs.existsSync(frontendContractsDir)) {
    fs.mkdirSync(frontendContractsDir, { recursive: true });
  }

  // Chain ID to network name mapping
  const chainIdToNetwork: { [key: number]: string } = {
    11155111: "sepolia",
    31337: "hardhat",
  };

  // Get all deployment directories
  if (!fs.existsSync(deploymentsDir)) {
    console.log("No deployments directory found. Skipping artifact generation.");
    return;
  }

  const deploymentDirs = fs.readdirSync(deploymentsDir, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name);

  if (deploymentDirs.length === 0) {
    console.log("No deployment networks found. Skipping artifact generation.");
    return;
  }

  const addresses: { [chainId: number]: { [contractName: string]: string } } = {};
  let contractABI: any = null;
  let contractName = "";

  // Process each network deployment
  for (const networkDir of deploymentDirs) {
    const networkPath = path.join(deploymentsDir, networkDir);
    const deploymentFiles = fs.readdirSync(networkPath)
      .filter((file) => file.endsWith(".json") && file !== ".chainId");

    // Try to determine chainId from network name or .chainId file
    let chainId: number | null = null;
    const chainIdFile = path.join(networkPath, ".chainId");
    if (fs.existsSync(chainIdFile)) {
      chainId = parseInt(fs.readFileSync(chainIdFile, "utf-8").trim());
    } else {
      // Try to map network name to chainId
      const networkName = networkDir.toLowerCase();
      for (const [id, name] of Object.entries(chainIdToNetwork)) {
        if (name === networkName) {
          chainId = parseInt(id);
          break;
        }
      }
    }

    if (!chainId) {
      console.log(`Skipping network ${networkDir}: Could not determine chainId`);
      continue;
    }

    // Process deployment files
    for (const deploymentFile of deploymentFiles) {
      const deploymentPath = path.join(networkPath, deploymentFile);
      const deploymentData = JSON.parse(fs.readFileSync(deploymentPath, "utf-8"));

      if (!deploymentData.address || deploymentData.address === "0x") {
        console.log(`Skipping ${deploymentFile} in ${networkDir}: No address found`);
        continue;
      }

      const name = path.basename(deploymentFile, ".json");
      
      if (!addresses[chainId]) {
        addresses[chainId] = {};
      }
      addresses[chainId][name] = deploymentData.address;

      // Use the first contract's ABI (assuming all contracts have the same ABI structure)
      if (!contractABI && deploymentData.abi) {
        contractABI = deploymentData.abi;
        contractName = name;
      }
    }
  }

  // Generate addresses file
  if (Object.keys(addresses).length > 0) {
    const addressesContent = `// Auto-generated file - do not edit manually
// This file is generated by backend/scripts/generate-frontend-artifacts.ts

export const CONTRACT_ADDRESSES: {
  [chainId: number]: {
    [contractName: string]: string;
  };
} = ${JSON.stringify(addresses, null, 2)};

// Helper function to get contract address by chainId and contract name
export function getContractAddress(
  chainId: number,
  contractName: string = "PsychoEvaluate"
): string | undefined {
  return CONTRACT_ADDRESSES[chainId]?.[contractName];
}
`;

    const addressesFilePath = path.join(frontendContractsDir, "addresses.ts");
    fs.writeFileSync(addressesFilePath, addressesContent);
    console.log(`✓ Generated addresses file: ${addressesFilePath}`);
    console.log(`  Networks: ${Object.keys(addresses).join(", ")}`);
  } else {
    console.log("No addresses found. Skipping addresses file generation.");
  }

  // Generate ABI file
  if (contractABI) {
    const abiContent = `// Auto-generated file - do not edit manually
// This file is generated by backend/scripts/generate-frontend-artifacts.ts
// Contract: ${contractName}

export const PSYCHO_EVALUATE_ABI = ${JSON.stringify(contractABI, null, 2)} as const;
`;

    const abiFilePath = path.join(frontendContractsDir, "PsychoEvaluate.abi.ts");
    fs.writeFileSync(abiFilePath, abiContent);
    console.log(`✓ Generated ABI file: ${abiFilePath}`);
  } else {
    console.log("No ABI found. Skipping ABI file generation.");
  }
}

// Register as Hardhat task
task("generate-frontend-artifacts", "Generate frontend ABI and address files from deployments")
  .setAction(async (taskArgs, hre) => {
    await hre.run("compile");
    await generateFrontendArtifacts(hre);
    console.log("Frontend artifacts generation completed!");
  });

export default generateFrontendArtifacts;

