// Auto-generated file - do not edit manually
// This file is generated by backend/scripts/generate-frontend-artifacts.ts

export const CONTRACT_ADDRESSES: {
  [chainId: number]: {
    [contractName: string]: string;
  };
} = {
  "11155111": {
    "PsychoEvaluate": "0x8107a8395066f3229719f5158475520aFa8F682f"
  }
};

// Helper function to get contract address by chainId and contract name
export function getContractAddress(
  chainId: number,
  contractName: string = "PsychoEvaluate"
): string | undefined {
  return CONTRACT_ADDRESSES[chainId]?.[contractName];
}
