/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PsychoEvaluateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getAssessment"
      | "getEScore"
      | "getNScore"
      | "getStressScore"
      | "hasAssessment"
      | "submitAssessment"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AssessmentSubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAssessment",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getEScore", values?: undefined): string;
  encodeFunctionData(functionFragment: "getNScore", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getStressScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasAssessment",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAssessment",
    values: [BytesLike[], BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssessment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEScore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStressScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAssessment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAssessment",
    data: BytesLike
  ): Result;
}

export namespace AssessmentSubmittedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PsychoEvaluate extends BaseContract {
  connect(runner?: ContractRunner | null): PsychoEvaluate;
  waitForDeployment(): Promise<this>;

  interface: PsychoEvaluateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getAssessment: TypedContractMethod<
    [],
    [
      [string, string, string, bigint] & {
        stressScore: string;
        eScore: string;
        nScore: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEScore: TypedContractMethod<[], [string], "view">;

  getNScore: TypedContractMethod<[], [string], "view">;

  getStressScore: TypedContractMethod<[], [string], "view">;

  hasAssessment: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  submitAssessment: TypedContractMethod<
    [encryptedAnswers: BytesLike[], inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAssessment"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint] & {
        stressScore: string;
        eScore: string;
        nScore: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getNScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getStressScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasAssessment"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitAssessment"
  ): TypedContractMethod<
    [encryptedAnswers: BytesLike[], inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AssessmentSubmitted"
  ): TypedContractEvent<
    AssessmentSubmittedEvent.InputTuple,
    AssessmentSubmittedEvent.OutputTuple,
    AssessmentSubmittedEvent.OutputObject
  >;

  filters: {
    "AssessmentSubmitted(address,uint256)": TypedContractEvent<
      AssessmentSubmittedEvent.InputTuple,
      AssessmentSubmittedEvent.OutputTuple,
      AssessmentSubmittedEvent.OutputObject
    >;
    AssessmentSubmitted: TypedContractEvent<
      AssessmentSubmittedEvent.InputTuple,
      AssessmentSubmittedEvent.OutputTuple,
      AssessmentSubmittedEvent.OutputObject
    >;
  };
}
